/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gushi/': RouteRecordInfo<
      '/gushi/',
      '/gushi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Blender是一款免费开源、功能全面的 3D 创作套件': RouteRecordInfo<
      '/posts/Blender是一款免费开源、功能全面的 3D 创作套件',
      '/posts/Blender是一款免费开源、功能全面的 3D 创作套件',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Every thing一款免费、轻量级的本地文件搜索工具': RouteRecordInfo<
      '/posts/Every thing一款免费、轻量级的本地文件搜索工具',
      '/posts/Every thing一款免费、轻量级的本地文件搜索工具',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Hexo vs Valaxy：静态博客框架的现代之争': RouteRecordInfo<
      '/posts/Hexo vs Valaxy：静态博客框架的现代之争',
      '/posts/Hexo vs Valaxy：静态博客框架的现代之争',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件': RouteRecordInfo<
      '/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件',
      '/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Motrix 是一款开源、跨平台的下载工具': RouteRecordInfo<
      '/posts/Motrix 是一款开源、跨平台的下载工具',
      '/posts/Motrix 是一款开源、跨平台的下载工具',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/VLC Media Player一款开源的多媒体播放器': RouteRecordInfo<
      '/posts/VLC Media Player一款开源的多媒体播放器',
      '/posts/VLC Media Player一款开源的多媒体播放器',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器': RouteRecordInfo<
      '/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器',
      '/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/如何刷入手机GSI固件': RouteRecordInfo<
      '/posts/如何刷入手机GSI固件',
      '/posts/如何刷入手机GSI固件',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！': RouteRecordInfo<
      '/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！',
      '/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/流行的Markdown编辑器推荐': RouteRecordInfo<
      '/posts/流行的Markdown编辑器推荐',
      '/posts/流行的Markdown编辑器推荐',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.8_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.8_@babel+parser_be336219f9fb04387b7133585c74b379/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
    }
    'pages/gushi/index.md': {
      routes:
        | '/gushi/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.8_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.8_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/Blender是一款免费开源、功能全面的 3D 创作套件.md': {
      routes:
        | '/posts/Blender是一款免费开源、功能全面的 3D 创作套件'
      views:
        | never
    }
    'pages/posts/Every thing一款免费、轻量级的本地文件搜索工具.md': {
      routes:
        | '/posts/Every thing一款免费、轻量级的本地文件搜索工具'
      views:
        | never
    }
    'pages/posts/Hexo vs Valaxy：静态博客框架的现代之争.md': {
      routes:
        | '/posts/Hexo vs Valaxy：静态博客框架的现代之争'
      views:
        | never
    }
    'pages/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件.md': {
      routes:
        | '/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件'
      views:
        | never
    }
    'pages/posts/Motrix 是一款开源、跨平台的下载工具.md': {
      routes:
        | '/posts/Motrix 是一款开源、跨平台的下载工具'
      views:
        | never
    }
    'pages/posts/VLC Media Player一款开源的多媒体播放器.md': {
      routes:
        | '/posts/VLC Media Player一款开源的多媒体播放器'
      views:
        | never
    }
    'pages/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器.md': {
      routes:
        | '/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器'
      views:
        | never
    }
    'pages/posts/如何刷入手机GSI固件.md': {
      routes:
        | '/posts/如何刷入手机GSI固件'
      views:
        | never
    }
    'pages/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！.md': {
      routes:
        | '/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！'
      views:
        | never
    }
    'pages/posts/流行的Markdown编辑器推荐.md': {
      routes:
        | '/posts/流行的Markdown编辑器推荐'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
