/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/test1': RouteRecordInfo<'/albums/test1', '/albums/test1', Record<never, never>, Record<never, never>>,
    '/albums/test2': RouteRecordInfo<'/albums/test2', '/albums/test2', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/gushi/': RouteRecordInfo<'/gushi/', '/gushi', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/1': RouteRecordInfo<'/posts/1', '/posts/1', Record<never, never>, Record<never, never>>,
    '/posts/10': RouteRecordInfo<'/posts/10', '/posts/10', Record<never, never>, Record<never, never>>,
    '/posts/2': RouteRecordInfo<'/posts/2', '/posts/2', Record<never, never>, Record<never, never>>,
    '/posts/3': RouteRecordInfo<'/posts/3', '/posts/3', Record<never, never>, Record<never, never>>,
    '/posts/4': RouteRecordInfo<'/posts/4', '/posts/4', Record<never, never>, Record<never, never>>,
    '/posts/5': RouteRecordInfo<'/posts/5', '/posts/5', Record<never, never>, Record<never, never>>,
    '/posts/6': RouteRecordInfo<'/posts/6', '/posts/6', Record<never, never>, Record<never, never>>,
    '/posts/7': RouteRecordInfo<'/posts/7', '/posts/7', Record<never, never>, Record<never, never>>,
    '/posts/8': RouteRecordInfo<'/posts/8', '/posts/8', Record<never, never>, Record<never, never>>,
    '/posts/9': RouteRecordInfo<'/posts/9', '/posts/9', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
