/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/test1': RouteRecordInfo<'/albums/test1', '/albums/test1', Record<never, never>, Record<never, never>>,
    '/albums/test2': RouteRecordInfo<'/albums/test2', '/albums/test2', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/gushi/': RouteRecordInfo<'/gushi/', '/gushi', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/pinglun/PostLayout': RouteRecordInfo<'/pinglun/PostLayout', '/pinglun/PostLayout', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/Blender是一款免费开源、功能全面的 3D 创作套件': RouteRecordInfo<'/posts/Blender是一款免费开源、功能全面的 3D 创作套件', '/posts/Blender是一款免费开源、功能全面的 3D 创作套件', Record<never, never>, Record<never, never>>,
    '/posts/Every thing一款免费、轻量级的本地文件搜索工具': RouteRecordInfo<'/posts/Every thing一款免费、轻量级的本地文件搜索工具', '/posts/Every thing一款免费、轻量级的本地文件搜索工具', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Hexo vs Valaxy：静态博客框架的现代之争': RouteRecordInfo<'/posts/Hexo vs Valaxy：静态博客框架的现代之争', '/posts/Hexo vs Valaxy：静态博客框架的现代之争', Record<never, never>, Record<never, never>>,
    '/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件': RouteRecordInfo<'/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件', '/posts/LibreOffice一款功能强大且完全免费的开源办公软件套件', Record<never, never>, Record<never, never>>,
    '/posts/Motrix 是一款开源、跨平台的下载工具': RouteRecordInfo<'/posts/Motrix 是一款开源、跨平台的下载工具', '/posts/Motrix 是一款开源、跨平台的下载工具', Record<never, never>, Record<never, never>>,
    '/posts/VLC Media Player一款开源的多媒体播放器': RouteRecordInfo<'/posts/VLC Media Player一款开源的多媒体播放器', '/posts/VLC Media Player一款开源的多媒体播放器', Record<never, never>, Record<never, never>>,
    '/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器': RouteRecordInfo<'/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器', '/posts/VS Code微软开发的一款免费、开源、跨平台的代码编辑器', Record<never, never>, Record<never, never>>,
    '/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！': RouteRecordInfo<'/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！', '/posts/手机本地部署 DeepSeek 模型指南：离线运行你的“AI大脑”！', Record<never, never>, Record<never, never>>,
    '/posts/流行的Markdown编辑器推荐': RouteRecordInfo<'/posts/流行的Markdown编辑器推荐', '/posts/流行的Markdown编辑器推荐', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
